Models/Cachorros.cs
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Routing;
using System.Drawing;
using System.Runtime.ConstrainedExecution;

namespace WebApplication1.Models
{
    public class Cachorros
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string genero { get; set; }
        public int ano_nascimento { get; set; }
        public string pedigree { get; set; }
        public string cor { get; set; }
        public string porte { get; set; }
        public string descrição { get; set; }
        public string foto { get; set; }
        public string foto1 { get; set; }
        public string foto2 { get; set; }
        public string foto3 { get; set; }

        public string raca { get; set; }

        public Cachorros()
        {
            this.id = 0;
            this.nome = string.Empty;
            this.genero = string.Empty;
            this.ano_nascimento = 0;
            this.pedigree = string.Empty;
            this.cor = string.Empty;
            this.porte = string.Empty;
            this.descrição = string.Empty;
            this.foto = string.Empty;
            this.foto1 = string.Empty;
            this.foto2 = string.Empty;
            this.foto3 = string.Empty;
            this.raca = string.Empty;
        }
        
    }
}

Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Login.cs
namespace WebApplication1.Models
{
    public class Login
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string TipoUsuario { get; set; }

        public Login()
        {
            this.Id = 0;
            this.Usuario = "";
            this.Senha = string.Empty;
            this.TipoUsuario = string.Empty;
        }
    }
}

Models/LoginResultado.cs
namespace WebApplication1.Models
{
    public class LoginResultado
    {
        public bool Sucesso { get; set; }
        public int Id { get; set; }
        public string TipoUsuario { get; set; }

        // public int QuantidadeItensCarrinho { get; set; }

        public LoginResultado()
        {            
            Id = 0;
            TipoUsuario = "";
        }
    }
}

Controllers/CachorroController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Repositories;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class CachorroController : Controller
    {
        // GET: Cachorro
        private readonly Repositories.ADO.SQL_SERVER.Cachorro repository;

        public CachorroController()
        {
            repository = new Repositories.ADO.SQL_SERVER.Cachorro();
        }
        public ActionResult Index()
        {
            return View(repository.get());
        }
        public ActionResult IndexAdm()
        {
            return View(repository.get());
        }
        // GET: Cachorro/Details/5
        public ActionResult Details(int id)
        {   
            return View(repository.getDetails(id));
        }

        // GET: Cachorro/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cachorro/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Cachorros cachorro)
        {
            try
            {
                repository.add(cachorro);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cachorro/Edit/5
        public ActionResult Edit(int id)
        {
            return View(this.repository.getEdit(id));
        }

        // POST: Cachorro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Models.Cachorros cachorro)
        {
            try
            {
                repository.edit(id, cachorro);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cachorro/Delete/5
        public ActionResult Delete(int id)
        {
            repository.delete(id);
            return View();
        }

        // POST: Cachorro/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Models.Cachorros cachorro)
        {
            try
            {
                repository.delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Time()
        {
            return View();
        }  
        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Configuration;
using WebApplication1.Models;
using WebApplication1.Repositories.ADO.SQLServer;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        private readonly Repositories.ADO.SQLServer.LoginDao repository;
        private readonly Services.ISessao sessao;

        public LoginController(IConfiguration configuration, Services.ISessao sessao)
        {            
            this.repository = new Repositories.ADO.SQLServer.LoginDao(configuration.GetConnectionString(Configurations.Appsettings.getKeyConnectionString()));
            this.sessao = sessao;
        }

        public IActionResult Login()
        {          
            // Se o usuário não estiver logado retorna a View() senão retorna para a página de início.
            return this.sessao.getTokenLogin() == null ? View() : RedirectToAction("Index","Home");            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Login login) 
        {
            #region "Login com controle de sessão."
            if (!string.IsNullOrEmpty(login.Usuario) && !string.IsNullOrEmpty(login.Senha))
            {
                if (this.repository.check(login))
                {
                    var loginResultado = repository.getTipo(login);
                    this.sessao.addTokenLogin(login);

                    if (loginResultado.TipoUsuario == "admin")
                        return RedirectToAction("Index", "Admin");
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError(string.Empty, "Usuário e/ou Senha Inválidos!");               
            }
            return View();

            #endregion

            #region "Login sem controle de sessão."
            /*
            if (!string.IsNullOrEmpty(login.Usuario) && !string.IsNullOrEmpty(login.Senha))
            { 
                if (this.repository.check(login))                   
                    return RedirectToAction("Index", "Home");
                return RedirectToAction("Index", "Carros");
            }

            ViewBag.Error = "Usuário e/ou Senha Inválidos!";
            return View();
            */
            #endregion

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Login login)
        {
            try
            {
                repository.add(login);
                return RedirectToAction(nameof(Login));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Create()
        {
            return View();
        }

        public IActionResult Logout() 
        {
            this.sessao.deleteTokenLogin();
            return RedirectToAction("Index", "Home"); 
        }

    }
}

Views/Admin/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

Views/Cachorro/Create.cshtml
@model WebApplication1.Models.Cachorros

@{
    ViewData["Title"] = "Create";
}



<div class="row">
    <div class="col-md-4">
        <h2 id="login-settings">Cadastro</h2>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="genero" class="control-label"></label>
                <input asp-for="genero" class="form-control" />
                <span asp-validation-for="genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ano_nascimento" class="control-label"></label>
                <input asp-for="ano_nascimento" class="form-control" />
                <span asp-validation-for="ano_nascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pedigree" class="control-label"></label>
                <input asp-for="pedigree" class="form-control" />
                <span asp-validation-for="pedigree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cor" class="control-label"></label>
                <input asp-for="cor" class="form-control" />
                <span asp-validation-for="cor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="porte" class="control-label"></label>
                <input asp-for="porte" class="form-control" />
                <span asp-validation-for="porte" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="raca" class="control-label"></label>
                <input asp-for="raca" class="form-control" />
                <span asp-validation-for="raca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descrição" class="control-label"></label>
                <input asp-for="descrição" class="form-control" />
                <span asp-validation-for="descrição" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto" class="control-label"></label>
                <input type="file" asp-for="foto" class="form-control" />
                <span asp-validation-for="foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto1" class="control-label"></label>
                <input type="file" asp-for="foto1" class="form-control" />
                <span asp-validation-for="foto1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto2" class="control-label"></label>
                <input type="file" asp-for="foto2" class="form-control" />
                <span asp-validation-for="foto2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto3" class="control-label"></label>
                <input type="file" asp-for="foto3" class="form-control" />
                <span asp-validation-for="foto3" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary custom-btn" />
            </div>
        </form>
    </div>
</div>

Views/Cachorro/Delete.cshtml
@model WebApplication1.Models.Cachorros

@{
    ViewData["Title"] = "Delete";
}


    
       
     
    <div class="row">
    <div class="delete-settings">
        
    <form asp-action="Delete">
        <h2 id="login-settings">Você tem certeza de que deseja excluir este cachorro?</h2>
    <input type="submit" value="Deletar" class="btn btn-primary custom-btn" /> 
        
    </form>
</div>
</div>

Views/Cachorro/Details.cshtml
@model WebApplication1.Models.Cachorros

@{
    ViewData["Title"] = "Details";
}

<dl class="row photos">

    <h2 id="login-settings">Descrição</h2>
 <div class="details-container">
    <div class="detail">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ano_nascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ano_nascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pedigree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pedigree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.porte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.porte)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.raca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.raca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descrição)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descrição)
        </dd>
    </div>

       

       <div class="photos-container">
        <dd class="col-sm-10">
            <img src="~/imgs/@Html.DisplayFor(model => model.foto)" />
        </dd>
        <dd class="col-sm-10">
            <img src="~/imgs/@Html.DisplayFor(model => model.foto1)" />
        </dd>
        <dd class="col-sm-10">
            <img src="~/imgs/@Html.DisplayFor(model => model.foto2)" />
        </dd>
        <dd class="col-sm-10">
            <img src="~/imgs/@Html.DisplayFor(model => model.foto3)" />
        </dd>
        </div>




 </div>
       
</dl>

Views/Cachorro/Edit.cshtml
@model WebApplication1.Models.Cachorros

@{
    ViewData["Title"] = "Edit";
}



<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <h2 id="login-settings">Edite seu Pet</h2>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="genero" class="control-label"></label>
                <input asp-for="genero" class="form-control" />
                <span asp-validation-for="genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ano_nascimento" class="control-label"></label>
                <input asp-for="ano_nascimento" class="form-control" />
                <span asp-validation-for="ano_nascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pedigree" class="control-label"></label>
                <input asp-for="pedigree" class="form-control" />
                <span asp-validation-for="pedigree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cor" class="control-label"></label>
                <input asp-for="cor" class="form-control" />
                <span asp-validation-for="cor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="porte" class="control-label"></label>
                <input asp-for="porte" class="form-control" />
                <span asp-validation-for="porte" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descrição" class="control-label"></label>
                <input asp-for="descrição" class="form-control" />
                <span asp-validation-for="descrição" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto" class="control-label"></label>
                <input type="file" asp-for="foto" class="form-control" />
                <span asp-validation-for="foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto1" class="control-label"></label>
                <input type="file" asp-for="foto1" class="form-control" />
                <span asp-validation-for="foto1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto2" class="control-label"></label>
                <input type="file" asp-for="foto2" class="form-control" />
                <span asp-validation-for="foto2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="foto3" class="control-label"></label>
                <input type="file" asp-for="foto3" class="form-control" />
                <span asp-validation-for="foto3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="raca" class="control-label"></label>
                <input asp-for="raca" class="form-control" />
                <span asp-validation-for="raca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary custom-btn" />
            </div>
        </form>
    </div>
</div>

Views/Cachorro/Index.cshtml
@model IEnumerable<WebApplication1.Models.Cachorros>
@using Newtonsoft.Json;
@{
    if (Context.Session.GetString("login") != null)
    {
        var resultadoSessao = Context.Session.GetString("login");
        var login = JsonConvert.DeserializeObject<Login>(resultadoSessao);
        var id = login.Id;
        var usuario = login.Usuario;
        var tipo = login.TipoUsuario;
        //... chamar todas as variáveis do LoginResultado no método getTipo do repositório LoginDao.

        ViewData["Id"] = id;
        ViewData["Usuario"] = usuario;
        ViewData["Tipo"] = tipo;
        // ... adicionar mais variáveis do tipo ViewData, se houver mais variáveis acima.
    }
}
@if (ViewData["Usuario"]?.ToString() != null)
{
    <div class="create-button-container">
        <a class="create-button" asp-action="Create" asp-controller="Cachorro">Cadastrar novo cão</a>
    </div>
}



<div class="cachorro-container">
    <div class="cachorro-list">
        @foreach (var item in Model)
        {
            <a asp-controller="Cachorro" asp-route-id="@item.id" asp-action="Details">
                <div class="cachorro-list-card">
                    <img src="~/imgs/@item.foto" alt="Cachorro 1">
                    <h2>@Html.DisplayFor(modelItem => item.nome)</h2>
                    

                    @if (ViewData["Usuario"]?.ToString() != null)
                    {
                        <div class="button-container">
                            <a class="edit-button" asp-action="Edit" asp-controller="Cachorro" asp-route-id="@item.id">Editar</a>
                            <a class="delete-button" asp-action="Delete" asp-controller="Cachorro" asp-route-id="@item.id">Deletar</a>
                        </div>
                    }
                </div>
            </a>
        }

    </div>
</div>

Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 id="tit-sobre">SOBRE</h1>
<div id="sobre-div">
    <div class="objetivo">
        <h3>Nossos objetivos?</h3>
        <p>
            Nosso site de acasalamento de cachorros oferecerá aos donos dos cães uma plataforma objetiva e segura
            para encontrar parceiros adequados para seu pet, com base em critérios de raça, idade, porte e Pedigree.
            
        </p>
    </div>
    <div class="facil">
        <h3>Fácil e prático!</h3>
        <p>Basta fazer o login e já poder procurar por um parceiro de seu interesse!</p>
    </div>
    <div class="vantagens">
        <h3>Quais as vantagens de usar o Conexão Canina?</h3>
        <p>
            Uma das principais vantagens é a garantia de que os filhotes gerados tenham boa saúde.
            Além da nossa exigência de um check-up realizado por um veterinário que ajudará a identificar problemas
            de saúde.
        </p>
    </div>
    <div class="etica">
        <h3>Ética e Bem-Estar Animal:</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Quisque suscipit felis id urna cursus, auctor vestibulum nunc efficitur. Vestibulum euismod quam vitae ex fermentum, 
            et iaculis felis feugiat. In hac habitasse platea dictumst.
        </p>
    </div>
    <div class="informacao">
        <h3>Informações sobre Cruzamentos:</h3>
        <p>
            Vivamus ut elit in ipsum dignissim cursus. Integer efficitur magna nec urna rhoncus, 
            eu sodales odio tristique. Suspendisse potenti. Praesent auctor metus vel arcu convallis, a efficitur nisi eleifend.
        </p>
    </div>
</div>

Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<main class="main-home">
    <div class="left-main">
        <img src="imgs/cao-main-resol.png"></img>
    </div>
    <div class="main-right">
        <div class="div-right">
            <h2>Encontre o par perfeito para o seu cão.</h2>
        </div>
        <nav class="nav-home">
                <div class= "nav-verCachorros">
                <div class="cachorros-info">
                    <span class=" texto-cachorro">
                        Venha conhecer nossos cachorros queridos!
                    </span>
                    <a class="botao-cachorro" asp-controller="Cachorro" asp-action="Index">Conhecer Cachorros</a>
                   
                    
                </div>
            </div>
        </nav>
    </div>
</main>
<h1 id="tit-sobre">SOBRE</h1>
<div id="sobre-div">
    <div class="objetivo">
        <h3>Nossos objetivos?</h3>
        <p>
            Nosso site de acasalamento de cachorros oferecerá aos donos dos cães uma plataforma objetiva e segura
            para encontrar parceiros adequados para seu pet, com base em critérios de raça, idade, porte e Pedigree.
        </p>
    </div>
    <div class="facil">
        <h3>Fácil e prático!</h3>
        <p>Basta fazer o login e já poder procurar por um parceiro de seu interesse!</p>
    </div>
    <div class="vantagens">
        <h3>Quais as vantagens de usar o Conexão Canina?</h3>
        <p>
            Uma das principais vantagens é a garantia de que os filhotes gerados tenham boa saúde.
            Além da nossa exigência de um check-up realizado por um veterinário que ajudará a identificar problemas
            de saúde.
        </p>
    </div>
</div>
<h1 id="team">EQUIPE</h1>
<div class="main-equipe">
    <div class="member">
        <img src="~/imgs/Enzo.jpg.jpeg" alt="Enzo Garbim">
        <h2>Enzo Garbim</h2>
        <p>Programador</p>
    </div>
    <div class="member">
        <img src="~/imgs/Cesar.jpeg" alt="César Prando">
        <h2>César Prando</h2>
        <p>Web Designer</p>
    </div>
    <div class="member">
        <img src="~/imgs/Nicolas.jpeg" alt="Nicolas Canonico">
        <h2>Nícolas Canonico</h2>
        <p>Programador</p>
    </div>
    <div class="member">
        <img src="~/imgs/Pedro.jpeg" alt="Pedro Garbim">
        <h2>Pedro Garbim</h2>
        <p>Instrutor</p>
    </div>
    <div class="member">
        <img src="~/imgs/Joao.jpeg" alt="João Veasey">
        <h2>João Veasey</h2>
        <p>Scrum Master</p>
    </div>

Views/Home/Time.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 id="team">EQUIPE</h1>
<div class="main-equipe">
    <div class="member">
        <img src="~/imgs/Enzo.jpg.jpeg" alt="Enzo Garbim">
        <h2>Enzo Garbim</h2>
        <p>Programador</p>
    </div>
    <div class="member">
        <img src="~/imgs/Cesar.jpeg" alt="César Prando">
        <h2>César Prando</h2>
        <p>Web Designer</p>
    </div>
    <div class="member">
        <img src="~/imgs/Nicolas.jpeg" alt="Nicolas Canonico">
        <h2>Nícolas Canonico</h2>
        <p>Programador</p>
    </div>
    <div class="member">
        <img src="~/imgs/Pedro.jpeg" alt="Pedro Garbim">
        <h2>Pedro Garbim</h2>
        <p>Instrutor</p>
    </div>
    <div class="member">
        <img src="~/imgs/Joao.jpeg" alt="João Veasey">
        <h2>João Veasey</h2>
        <p>Scrum Master</p>
    </div>
</div>

Views/Login/Create.cshtml
@model WebApplication1.Models.Login

@{
    ViewData["Title"] = "Create";
}





<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <h2 id="login-settings">Cadastro</h2>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-usuario">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-senha">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoUsuario" class="control-label"></label>
                <input asp-for="TipoUsuario" class="form-control" />
                <span asp-validation-for="TipoUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary custom-btn" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_Layout.cshtml
@using Newtonsoft.Json;

@{
    if (Context.Session.GetString("login") != null)
    {
        var resultadoSessao = Context.Session.GetString("login");
        var login = JsonConvert.DeserializeObject<Login>(resultadoSessao);
        var id = login.Id;
        var usuario = login.Usuario;
        var tipo = login.TipoUsuario;
        //... chamar todas as variáveis do LoginResultado no método getTipo do repositório LoginDao.

        ViewData["Id"] = id;
        ViewData["Usuario"] = usuario;
        ViewData["Tipo"] = tipo;
        // ... adicionar mais variáveis do tipo ViewData, se houver mais variáveis acima.
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/css/reset.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="~/css/cadastroCao.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/telaCruza.css" asp-append-version="true" /> 
<link rel="stylesheet" href="~/css/cachorro.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/detalhes.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/edit.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/delete.css" asp-append-version="true" />

</head>
<body>
    <header>
        <div class="left-header">
            <a asp-controller="Home" asp-action="Index">
            <img src="~/imgs/logoprojeto.png" alt="logo">
            </a>
        </div>
        <nav class="navheader">
            <ul>
               
                <li class="sobre"><a asp-controller="Home" asp-action="About" >Sobre</a></li>
                <li class="equipe"><a asp-controller="Home" asp-action="Time">Equipe</a></li>
                <li class="cachorro"><a asp-controller="Cachorro" asp-action="Index">Cachorros</a></li>
                <div class="user-info">
                @{
                    if (ViewData["Usuario"]?.ToString() != null)
                    {
                        <a class="sair-button" asp-controller="Login" asp-action="Logout">Sair&nbsp;<span class="fa fa-close"></span></a>
                        <br />
                        <span class="usuario">Olá @ViewData["Usuario"], seja Bem Vindo!</span>
                    }
                    else
                    {
                        <a class="entrar-button" asp-controller="Login" asp-action="Login">Entrar&nbsp;<span class="fa fa-folder-open-o"></span></a>
                    }
                
                }
                </div>
            </ul>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="rodape">
        <div>
            <h2>© Copyright Conexão Canina</h2>
            <h2>Desenvolvido por Grupo PETS</h2>
        </div>
        <div>
            <h2>Telefone: (16) 99999-9999</h2>
            <h2>e-Mail: conexaocanina@gmail.com</h2>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>